# Generated by Django 5.2.6 on 2025-09-20 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Familia',
                'verbose_name_plural': 'Familias',
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=200, verbose_name='Nombre vulgar')),
                ('scientific_name', models.CharField(max_length=200, unique=True, verbose_name='Nombre científico')),
                ('endangered', models.BooleanField(default=False, verbose_name='En peligro de extinción')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='species', to='crudZoo.family')),
            ],
            options={
                'verbose_name': 'Especie',
                'verbose_name_plural': 'Especies',
            },
        ),
        migrations.CreateModel(
            name='Zoo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('country', models.CharField(max_length=100, verbose_name='País')),
                ('size_m2', models.PositiveIntegerField(verbose_name='Tamaño (m2)')),
                ('annual_budget', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Presupuesto anual')),
                ('animals', models.ManyToManyField(blank=True, related_name='zoos', to='crudZoo.animal')),
            ],
            options={
                'verbose_name': 'Zoo',
                'verbose_name_plural': 'Zoos',
            },
        ),
    ]
